version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200 # Elasticsearch HTTP
    networks:
      - elk
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - 27023:27017 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=GErrjfirfndkFr
      - MONGO_INITDB_DATABASE=expertconnect_coach
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  auth_service:
    build: ./path-to-auth-service
    container_name: auth_service
    environment:
      DATABASE_URL: mongodb://root:GErrjfirfndkFr@mongodb:27017/expertconnect_coach
      KAFKA_URL: kafka:9092
    ports:
      - 3001:3000
    depends_on:
      - kafka

  payment_service:
    build: ./path-to-payment-service
    container_name: payment_service
    environment:
      DATABASE_URL: mongodb://root:GErrjfirfndkFr@mongodb:27017/expertconnect_coach
      KAFKA_URL: kafka:9092
    ports:
      - 3002:3000
    depends_on:
      - kafka

volumes:
  elasticsearch-data:
  mongodb-data:

networks:
  elk:
    driver: bridge
